### ISSUE TITLE
high ESS value but no convergence for phi and lnL

### ISSUE THREAD

**Issue by datou99** [bpp/bpp#118]
Hi,
I run the Multispecies Coalescent Model with Introgression on 1024 loci for four species with "burnin = 2000000, sampfreq = 2, nsample = 10000000".  Introgression was assigned to happen from one species to another one.  
The ESS values for both phi and lnL are high as 7,111 for phi and 33,324 for lnL. While neither phi nor lnL are convergent at last. phi keeps fluctuating between 0.1 to 0.9 through all of the 20000000 iterations and show no sign of convergence. So shold I run more iterations to make the phi estimation convergent ? or maybe I should change other parameters? 

Thanks in advance!
Fang

**Comment by ziheng-yang** [comment]
you can post your question at the discusison group:
https://groups.google.com/forum/#!forum/bpp-discussion-group
and attach the control file.  
ziheng

**Comment by ziheng-yang** [comment]
this is a user query, not an issue.  closed.
