### ISSUE TITLE
phase option yields high theta estimates

### ISSUE THREAD

**Issue by eaton-lab** [bpp/bpp#153]
Hi @xflouris and developers, 

I've been testing BPP algorithm 00 on sequence data simulated with the bpp simulator and also with an alternative msprime-based simulator (ipcoal). I am finding a strange difference in results particularly with respect to the use of phasing, summarized below:

- OK - sim phased sequences with bpp, estimate params in bpp with phase=0... yields: (theta=0.005, root tau=0.0125)
- OK - sim phased sequences with ipcoal, estimate params in bpp with phase=0... yields: (theta=0.005, root tau=0.0125)
- OK - sim unphased diploid data with bpp, estimate params in bpp with phase=1... yields:  (theta=0.005, root tau=0.0125)
- PROBLEM - sim unphased diploid data with ipcoal, estimate params in bpp with phase=1... yields:  (theta=0.011, root tau=0.015)

I've double checked that the diploid sequences simulated with ipcoal contain IUPAC characters for heterozygous sites representing differences among two randomly joined haploid sequences in a population. I also verified that the ipcoal simulated data has theta=0.005 and tau=0.0125 by measuring diversity and divergence of the sequences. Creating unphased diploid sequences from phased haplotypes should be as easy as the following, right?:  
```
haplo_0    AAACTTGG
haplo_1    AACCTAGG
```
```
diplo_0    AAKCTWGG
```
Does BPP do something different when simulating diploid unphased sequences? Does it make a different assumption about the population being diploid when phasing (e.g., coalescence rate 1/2N versus 1/N)? I'm trying to figure out why these results are so different (and approximately off by 2X in the theta estimates)...

#### Example files
I've uploaded some example files that can be downloaded and tested below:

- [unphased ipcoal ctlfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-unphased-diploid-ctl-txt)
- [unphased ipcoal imap](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-unphased-diploid-imap-txt)
- [unphased ipcoal seqfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-unphased-diploid-seqs-txt)
-------------------------
- [phased ipcoal ctlfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-phased-diploid-ctl-txt)
- [phased ipcoal imap](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-phased-diploid-imap-txt)
- [phased ipcoal seqfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-phased-diploid-seqs-txt)
-------------------------
- [unphased bpp simulate ctl](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-diplo-ctl-txt)
- [phased bpp simulate ctl](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-haplo-ctl-txt)
-------------------------
- [unphased bpp infer ctl](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-infer-diplo-ctl-txt)
- [unphased bpp infer imap](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-diplo-imap-txt)
- [unphased bpp infer seqfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-diplo-seqs-txt)
-------------------------
- [phased bpp infer ctl](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-infer-haplo-ctl-txt)
- [phased bpp infer imap](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-haplo-imap-txt)
- [phased bpp infer seqfile](https://gist.github.com/eaton-lab/c12642b894e7825d662d4f1cddf97b90#file-bpp-sim-haplo-seqs-txt)

#### Commands

```bash
bpp-4.4.0-linux-x86_64/bin/bpp -cfile unphased.ctl.txt
```

```bash
bpp-4.4.0-linux-x86_64/bin/bpp -cfile unphased.ctl.txt
```

```bash
bpp-4.4.0-linux-x86_64/bin/bpp --simulate bpp-sim-haplo.ctl.txt
bpp-4.4.0-linux-x86_64/bin/bpp --cfile bpp-infer-haplo.ctl.txt
```

```bash
bpp-4.4.0-linux-x86_64/bin/bpp --simulate bpp-sim-diplo.ctl.txt
bpp-4.4.0-linux-x86_64/bin/bpp --cfile bpp-infer-diplo.ctl.txt
```

Here are the results from the end the `.out` file I get from each of these tests:
**(BUG: this seems to mislabel the columns, I assume it should have Theta for every node (here approximately 0.005), and then Tau only for the internal nodes)**

#### `bpp-sim-haplo`: 8 phased diploid sequences simulated with bpp: results are good
```
Node (+1)     Theta        Tau    Label
0          0.000000   0.005158    r0
1          0.000000   0.005298    r1
2          0.000000   0.005051    r2
3          0.000000   0.004756    r3
4          0.000000   0.005058    r4
5          0.012423   0.004107    r4r3r0r1r2
6          0.007290   0.005407    r4r3
7          0.004997   0.005224    r0r1r2
8          0.002548   0.004807    r0r1
```

#### `bpp-sim-diplo`: 4 unphased diploid sequences simulated with bpp: results are good
```
Node (+1)     Theta        Tau    Label
0          0.000000   0.005674    r0
1          0.000000   0.005260    r1
2          0.000000   0.005199    r2
3          0.000000   0.005051    r3
4          0.000000   0.004854    r4
5          0.012609   0.005945    r3r4r0r1r2
6          0.007626   0.004548    r3r4
7          0.005148   0.005130    r0r1r2
8          0.002460   0.005471    r0r1
```

#### `phased` 8 phased diploid sequences simulated with ipcoal: results are *pretty* good
```
Node (+1)     Theta        Tau    Label
0          0.000000   0.005287    r0
1          0.000000   0.005249    r1
2          0.000000   0.004845    r2
3          0.000000   0.005431    r3
4          0.000000   0.005095    r4
5          0.011645   0.006219    r4r3r2r1r0
6          0.007227   0.005429    r4r3
7          0.004817   0.004574    r2r1r0
8          0.002541   0.005343    r1r0
```

#### 'unphased` 4 unphased diploid sequences simulated with ipcoal: INCORRECT
```
Node (+1)     Theta        Tau    Label
0          0.000000   0.013055    r0
1          0.000000   0.012468    r1
2          0.000000   0.010575    r2
3          0.000000   0.011800    r3
4          0.000000   0.010781    r4
5          0.015259   0.006270    r4r3r2r1r0       <- 0.015 should be 0.0125, and other taus off as well
6          0.011405   0.004622    r4r3
7          0.008090   0.004502    r2r1r0
8          0.004953   0.007016    r1r0
```

I examined the unphased diploid sequences simulated by both programs. The average heterozygosity of each sample is correctly 0.005 in both datasets. 

Any thoughts on why the two simulators are leading to such different results?

Thanks,
Deren

**Comment by ziheng-yang** [comment]
hi deren,
i have not used msprime, and am curious what you find out.
with the phase option (phase = 1 1 1 1 1), bpp/simulate will generate twice as many fully resolved sequences and then collapse a pair of them from the same species into one diploid unresolved sequence, exactly as you explained.  both versions of the sequence alignments are printed out automatically, so you can check.  those options were tested only recently when we did this simulation paper for sys bio:
https://academic.oup.com/sysbio/advance-article/doi/10.1093/sysbio/syab047/6304882

i think you should comment out the lile 
alphaprior = 1 1
but it should not make any difference.  it is about gamma rates for sites in the same sequence.  i can't see anything obviously wrong.  you can run the same analysis a few times to see whether there is a convergence/mixing issue, although this does not look likely.  yes, the theta and tau columns are flipped.  in the last block of results ('unphased` 4 unphased diploid sequences simulated with ipcoal: INCORRECT) you have theta for modern species to be >1%, more than twice as large as 0.005.  given that modern theta's are so easy to estimate, something must be very wrong.

i don't really have good ideas, but here are a few debugging ideas.  i suggest that you check the case of 1 species (with only 1 parameter theta), or 2 species.  you can use 1000 loci instead of 200, to rule out the impact of the prior.  perhaps multiply tau and theta by 10 so that each locus is more informative, just to make it even easier to tell that something is definitely wrong.  one replicate dataset should be enough so there is no need to simulate 100.

i'll make more comments if anything comes to mind.
ziheng

**Comment by eaton-lab** [comment]
Thanks @ziheng-yang, I'll try some simpler simulations and let you know what I find.

**Comment by eaton-lab** [comment]
@ziheng-yang , I found it was a bug in my simulation code! I was converting to IUPAC codes incorrectly. I am now getting correct results from BPP. Sorry for the bother, thanks for your help.
