### ISSUE TITLE
--bfdriver option

### ISSUE THREAD

**Issue by svedwards** [bpp/bpp#160]
Dear Tomas -

I see that in issue #129 there is a --bfdriver and --points options. Is there any documentation on how to put these into the control file? I didn't see any - adding just the options alone results in an error. I am hoping to compare A00 models with and without among-locus rate variation. Thanks for any assistance!

Scott

**Comment by svedwards** [comment]
Tomas -

No need to reply. I was able to get the power posterior bayes factor test working with Mario's bppr package. 

Best,

Scott

**Comment by xflouris** [comment]
Hello Scott,

I have just added the --bfdriver option in BPP as described in issue #129 . It is available in the [dev](https://github.com/bpp/bpp/tree/dev) branch (v4.5.0) although I will create a new release on the main branch in the next days.
**Note:** The `BayesFactorBeta` option was already in BPP 4. It is only the generation of control files with different betas that was missing.

The syntax is:
```
bpp --bfdriver FILENAME --points N
```

where FILENAME is a control file and N the number of G-L quadrature points. The program will create N control files with different `BayesFactorBeta=XXX` beta values keeping the original one intact. You can then run each control file, and it will sample from a different power posterior distribution. The bfdriver option also creates a CSV file (betaweights.csv) that contains all beta values and their weights. The third column in the file must then be filled with the ElnfX value from the output of each of the N runs. The marginal likelihood can then be estimated by summing weight*ElnfX/2 over the N points.

There are some (outdated) notes in Appendix A of the [BPP manual](https://github.com/bpp/bpp/raw/master/bppDOC.pdf) which assumed BFdriver as a different program [i.e. part (a) about compiling and part (b) about running BFdriver].

Best regards,
Tomas
