### ISSUE TITLE
M1 Mac compilation

### ISSUE THREAD

**Issue by henicorhina** [bpp/bpp#182]
Are there plans to support compilation on newer M1 Macs? Or has anyone figured out a way to install BPP on an M1 Mac?

**Comment by xflouris** [comment]
Hi @henicorhina ,
yes, we do plan to port the code for ARM but it will take a few months until that's done.
Best,
Tomas

**Comment by henicorhina** [comment]
Thanks! Emulation mode did the trick

**Comment by xflouris** [comment]
Added vectorized implementation for ARM64 neon - closing issue
