### ISSUE TITLE
Impact of estimating population size and divergence time using A00

### ISSUE THREAD

**Issue by SunJJ230120** [bpp/bpp#201]
Hello, Developer,

Thank you for developing this program! I am currently using BPP's A00 model to estimate population divergence times and population sizes. I've noticed there are significant differences in the number of individuals among populations, and I'm concerned that this might affect the estimation of divergence times and population sizes. I'm puzzled about whether sample size will impact the related analysis. If possible, I hope you can provide some guidance or suggestions to ensure the accuracy of my analysis results.

Looking forward to your response.

Jing-Jing Sun

**Comment by ziheng-yang** [comment]
please post your question at the bpp discussion group.  the github site is for reporting bugs or issues.
it's unclear what your concerns are.  
the sampling will affect the information content.  for example if you have only one sequence per species per locus, you can't estimate the population size for the modern species.  but estimation is possible if you have at least two sequences from the same population.  
you can look at the following simulation paper, which examine the information content when the number of loci, the number of sequences, the number of sites, etc. change.

Huang J, Flouri T, Yang Z. (Huang2020 co-authors). 2020. A simulation study to examine the information content in phylogenomic datasets under the multispecies coalescent model. Mol. Biol. Evol. 37:3211-3224.

ziheng yang
