### ISSUE TITLE
Savage-Dickey density ratio

### ISSUE THREAD

**Issue by mprebus** [bpp/bpp#202]
Is there an example script for calculating the Savage-Dickey density ratio from MCMC output of the MSCi model?

**Comment by xflouris** [comment]
Hi @mprebus ,
yes, please check the last part of the  [hypothesis testing tutorial](https://github.com/Pas-Kapli/phylophysalia2023/wiki/Hypothesis-testing-with-BPP) on Savage-Dickey.
There's a script there, you'll need to adapt the prior variable depending on your cutoff and beta prior (see the comments within the script).
Best,
Tomas

**Comment by mprebus** [comment]
Thank you!
