### ISSUE TITLE
Undocumented assertion

### ISSUE THREAD

**Issue by Becheler** [bpp/bpp#92]
Hi !

I just began to use BPP and everything is pretty new to me. I guess I obviously did something wrong in the configuration file to get this assertion failure, but the current program version does not really help me going to fix it :)

```
Running MCMC... 0%bpp: gtree.c:1343: propose_ages: Assertion `maxage > minage' failed.
Aborted (core dumped)
```

I'm wondering what could possibly be wrong in my configuration file or dataset to trigger this kind of failure. Perhaps replace the assertion by an exception delivering some explanations and maybe recommendations to the user ?

Thank you !

**Comment by xflouris** [comment]
Hi @Becheler ,
thank you for the report. I believe this is generated from some older version of BPP from the 'dev' branch while I was adding some new functionality and making sure through assertions that the unexpected does not happen. The assertion you indicate is not present in the current version in the master branch.

What is the version you are using? I would suggest to re-clone/pull the current version from the master branch (version 4.1.2). 
I intend to create 'releases' with precompiled binaries in the next couple of days.

Best regards,
Tomas

**Comment by Becheler** [comment]
Hi,
I cloned the project again, and the problem seems to persist.
The assertion is located in gtree.c file, line 2792, and is still present in the master branch.

Best,
Arno

**Comment by brannala** [comment]
This is probably due to the configuration file. The new version uses an
inverse gamma prior on the root age. Tyy the following:

the priors

    thetaprior = 2 2000  
      tauprior = 2 2000    
Dirichlet(a) for other tau's


are for 3.3 or earlier.  change to

    thetaprior = 3 0.002  # invgamma(a, b) for theta
      tauprior =  3 0.002      # invgamma(a, b) for root tau & 
Dirichlet(a) for other tau's



Arnaud Becheler writes:

> Hi, I cloned the project again, and the problem seems to persist. The assertion is located in gtree.c file, line 2792, and is still present in the master branch.
> Best, Arno
> — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.


-- 
Bruce Rannala
Professor, Evolution & Ecology, UC Davis

**Comment by Becheler** [comment]
Hi ! Thank you so much for your help, it works now ! It was indeed related to an inconsistency between the priors and the underlying sequences generating process. :)

Best regards,
Arno
